// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC84KM8ExNKsFvcHCyE2ffx8Ptt3fpq_I4',
    appId: '1:762010764882:android:982158c62a3b5c8604018b',
    messagingSenderId: '762010764882',
    projectId: 'foodly-flutter-publish',
    databaseURL: 'https://foodly-flutter-publish-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodly-flutter-publish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyb7g4wYt-NBe1KYwt-1DY5dFUqPY_L-Y',
    appId: '1:762010764882:ios:c14bce05e38dd75a04018b',
    messagingSenderId: '762010764882',
    projectId: 'foodly-flutter-publish',
    databaseURL: 'https://foodly-flutter-publish-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodly-flutter-publish.appspot.com',
    iosClientId: '762010764882-hr30rvfhslgi6v328ivabqaf2uateiev.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.foodlyRestaurant',
  );
}
