name: foodly_restaurant

description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  flutter_svg: ^2.0.9
  lottie: ^3.1.1
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  firebase_core: ^2.24.0
  firebase_database: ^10.3.8
  device_preview: ^1.1.0
  otp_text_field: ^1.1.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
    - .env.development
    - .env.production